openapi: 3.0.0
info:
  version: 1.0.0
  title: Manabiya AI API Document
  description: This is Manabiya AI Agent API Document.
servers:
  - url: http://localhost:3001
paths:
  /:
    get:
      description: |
        Display Hello AI
      operationId: cmd_hello_ai
      responses:
        '200':
          description: Outputs AI Agent's self-introduction text.
          content:
            plain/text:
              example: Hello AI.
  /create_agenda:
    post:
      description: |
        Create class resume data from textbook data.
        Specify the target lesson.
      operationId: cmd_create_agenda
      parameters: []
      requestBody:
        description: create agenda for lesson.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefrenceRequest'
            example:
              reference: "2023/1-1/common/english/lessons/ayiiF5ZAkPKCV6Y99Dau"
              start_page: 1
              finish_page: 3
              notice: ["nama.nama", "name.name", "name.name", "namae.nmamae"]
      responses:
        '200':
          description: Return resume data path.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateResult'
              example:
                reference: "2023/1-1/common/english/lessons/ayiiF5ZAkPKCV6Y99Dau"
                feilds: {
                  agenda: "agenda_draft"
                }
                
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /create_questions:
    post:
      description: |
        Create quizzes from textbook data and class audio data.
      operationId: cmd_create_questions
      parameters: []
      requestBody:
        description: create questions after lesson.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefrenceRequest'
            example:
              reference: "2023/1-1/common/english/lessons/ayiiF5ZAkPKCV6Y99Dau"
              notice: ["nama.nama", "name.name", "name.name", "namae.nmamae"]
      responses:
        '200':
          description: Return test data path.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateResult'
              example:
                reference: "2023/1-1/common/english/lessons/ayiiF5ZAkPKCV6Y99Dau"
                feilds: {
                  questions: "questions_draft"
                }
        default:
          description: unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    RefrenceRequest:
      type: object
      required:
        - reference
        - start_page
        - finish_page
      properties:
        reference:
          type: string
          description: firestore reference path.
          example: '2023/1-1/common/english/lessons/ayiiF5ZAkPKCV6Y99Dau'
        start_page:
          type: integer
          description: first page of lesson.
        finish_page:
          type: integer
          description: last page of lesson.
        notice:
          type: array
          description: list of notice user.name.
          items:
            type: string
    CreateResult:
      type: object
      required:
        - reference
        - field
      properties:
        reference:
          type: string
          description: created data reference path.
          example: '2023/1-1/common/english/lessons/ayiiF5ZAkPKCV6Y99Dau'
        field:
          type: object
          description: stored field names.
          properties:
            agenda:
              type: string
              description: agenda field name.
            questions:
              type: string
              description: questions field name.
            results:
              type: string
              description: results field name.
    Error:
      type: object
      required:
        - code
        - type
        - message
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
externalDocs:
  description: Find out more about Swagger.
  url: http://swagger.io
